DISCOVERY_HOSTNAME: discovery.local
greeting: "안녕하세요~"

---
spring:
  profiles: dev

greeting: "(DEV) CUSTOMER 안녕하세요~ 좋은아침이에요."


---
spring:
  profiles: prod

greeting: "(PROD) CUSTOMER 안녕하세요~"


---
spring:
  profiles: aws.dev
DISCOVERY_HOSTNAME: poc.discovery.aws
greeting: "[AWS:DEVELOPMENT:CUSTOMER-SERVICE] 안녕하세요~"


---
spring:
  profiles: aws.prod
DISCOVERY_HOSTNAME: poc.discovery.aws
greeting: "[AWS:PRODUCTION:CUSTOMER-SERVICE] 안녕하세요~"