GATEWAY_HOSTNAME: local.gateway
DISCOVERY_HOSTNAME: local.discovery
CUSTOMER_HOSTNAME: localhost

---
spring:
  profiles: aws.dev
GATEWAY_HOSTNAME: poc.gateway.aws
DISCOVERY_HOSTNAME: poc.discovery.aws
CUSTOMER_HOSTNAME: poc.customerserver.aws
PRODUCT_HOSTNAME: poc.productserver.aws


---
spring:
  profiles: aws.prod
GATEWAY_HOSTNAME: poc.gateway.aws
DISCOVERY_HOSTNAME: poc.discovery.aws
CUSTOMER_HOSTNAME: poc.customerserver.aws
PRODUCT_HOSTNAME: poc.productserver.aws

